#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: Polymorphism-aware phylogenetic models
#+subtitle: Workshop, MIC-Phy 2021
#+author: Dominik Schrempf
#+email: dominik.schrempf@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.4.4)

#+startup: beamer
#+latex_class: myPresentation
#+latex_class_options: [aspectratio=169,minted]
#+latex_header: \addbibresource{~/Evolutionary-Biology/Bibliography/bibliography.bib}
#+latex_header_extra: \titlegraphic{\includegraphics[width=10em]{logos/elte}}
#+latex_compiler: unused; see `org-latex-pdf-process'

#+columns: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)
#+date: February 16, 2021
#+description:
#+keywords:
#+options: H:1

* Introduction
This workshop is [[https://github.com/pomo-dev/micphy-workshop][available on GitHub]].
#+beamer: \vspace{2ex}

Our goal is to understand polymorphism-aware phylogenetic models (PoMo) and
learn how to apply PoMo to phylogenetic data.
#+beamer: \vspace{2ex}

In the course of this workshop, we will infer a phylogenetic tree from a test
data set using IQ-TREE2.
#+beamer: \vspace{2ex}

If you need help, please interrupt me anytime!

* Preparation - Command line shell
Basic knowledge of the command line shell of your choice is assumed.
- If you do not know basic commands such as =cd=, =ls=, or =less=, just follow
  the presentation.
- Otherwise, try to complete the workshop yourself.

In case you are lost:
- Have a look at the manual pages, if they exist.
  #+name: ManLess
  #+begin_src sh :exports code :results none
  man less
  #+end_src
- Read how commands are used.
  #+name: HelpLess
  #+begin_src sh :exports code :results none
  less --help
  #+end_src
  
* Preparation - Download workshop and data
Option 1: If you have =git= installed, use it.
#+name: Git
#+begin_src sh :exports code :results none :eval never
git clone https://github.com/pomo-dev/micphy-workshop.git
cd micphy-workshop
#+end_src

Option 2: Manually download the archive.
#+begin_src sh :exports code :results none :eval never
wget https://github.com/pomo-dev/micphy-workshop/archive/master.zip
unzip master.zip
cd micphy-workshop-master
#+end_src

The advantage of Option 1 is that you can update your working tree using =git
pull= (if I have to change something during the workshop).

* Preparation - Installation of IQ-TREE2
Option 1: Repository of your Linux distribution. For example, using Arch Linux
and the Arch User Repository.
#+name: IqTree2InstallFromRepository
#+begin_src sh :exports code :results none :eval never
yay -S iqtree
aura -A iqtree
#+end_src
#+beamer: \vspace{1ex}

Option 2: Download the binary executable from the [[http://www.iqtree.org/#download][IQ-TREE2 homepage]]. Make sure
that you have permission to execute the file (=chmod +x=), and that the
executable is either in your =PATH=, or that you give the path during execution.
#+name: IqTree2Test
#+begin_src sh :exports code :results none :eval never
iqtree2 --version
/path/to/iqtree2 --version
./relative/path/to/iqtree2 --version
#+end_src

* Preparation - Installation of IQ-TREE2
Option 3: Compile yourself (not shown).
#+beamer: \vspace{2ex}

Option 4 for script kiddies or experienced users: Use =nix-shell= and the
=shell.nix= expression provided in the base directory of the repository.

#+name: NixShell
#+begin_src sh :exports both :results output verbatim replace
nix-shell
#+end_src

#+RESULTS: NixShell
: Welcome to the MIC-Phy PoMo workshop.
: The following version of IQ-TREE2 is available:
: 
: IQ-TREE multicore version 2.1.2 COVID-edition for Linux 64-bit built Jan  1 1980
: Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
: Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
: 

* Preparation - Test IQ-TREE2 version
Depending on how you installed IQ-TREE2, please check that the version agrees
with the one I am using.

#+name: IqTree2Version
#+begin_src sh :exports both :results output verbatim replace
iqtree2 --version
# /path/to/iqtree2 --version
# ./relative/path/to/iqtree2 --version
#+end_src

#+RESULTS: IqTree2Version
: IQ-TREE multicore version 2.1.2 COVID-edition for Linux 64-bit built Jan  1 1980
: Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
: Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
: 

* Exercise - How to get help
- How to get help (IQ-TREE).

* Exercise - Run a DNA substitution model
- Run normal model.

* Exercise - Run PoMo
- Run PoMo.
- Find best N.
- Compare different DNA substitution models.
- Use gamma rate heterogeneity.
- Probably perform model test?

* Literature
:PROPERTIES:
:ID:       a3a4fe49-79a8-4618-bcae-655485ac54c4
:END:
#+attr_latex: :options [Advanced models with PoMo]
- PoMo :: textcite:DeMaio2015.
- Reversible PoMo :: textcite:Schrempf2016,Schrempf2017.
- Advanced models with PoMo :: textcite:Schrempf2019.
- IQ-TREE2 :: textcite:Minh2020a.

* Bibliography
:PROPERTIES:
:BEAMER_opt: allowframebreaks
:END:

#+begin_export latex
\printbibliography{}
#+end_export
